apiVersion: nagi.io/v1alpha1
kind: Conditions
metadata:
  name: greeting-check
spec:
  - name: file-exists
    type: Command
    run: [test, -f, greeting.txt]
---
apiVersion: nagi.io/v1alpha1
kind: Conditions
metadata:
  name: farewell-check
spec:
  - name: file-exists
    type: Command
    run: [test, -f, farewell.txt]
